import type { Product } from '../utils/types/products';

const products: Product[] = [
  {
    id: 'p1',
    name: 'Amino Keratin Shampoo',
    price: 380.00,
    description: 'Un shampoo enriquecido con aminoácidos y keratina para un cabello fuerte y saludable. Repara el daño y fortalece la fibra capilar.',
    images: [require('../assets/images/products/amino-keratin-shampoo.png')],
    rating: 4.8,
    reviewsCount: 150,
    category: 'Reparación y Fuerza',
    isFavorite: false,
  },
  {
    id: 'p2',
    name: 'Amino Keratin System',
    price: 399.00,
    description: 'Sistema completo de cuidado capilar para una reparación intensiva. Incluye shampoo y acondicionador.',
    images: [require('../assets/images/products/amino-keratin-system.png')],
    rating: 4.7,
    reviewsCount: 120,
    category: 'Reparación y Fuerza',
    isFavorite: false,
  },
  {
    id: 'p3',
    name: 'Amino Keratin Mask',
    price: 449.00,
    description: 'Mascarilla de tratamiento profundo que hidrata y restaura el cabello dañado, aportando suavidad y brillo.',
    images: [require('../assets/images/products/amino-keratin-mask.png')],
    rating: 4.6,
    reviewsCount: 95,
    category: 'Reparación y Fuerza',
    isFavorite: false,
  },
  {
    id: 'p4',
    name: 'Deep Nutrition Shampoo',
    price: 380.00,
    description: 'Shampoo con fórmula de nutrición intensa para cabellos secos y maltratados. Devuelve la vitalidad y el brillo.',
    images: [require('../assets/images/products/deep-nutrition-shampoo.png')],
    rating: 4.5,
    reviewsCount: 88,
    category: 'Hidratación y Nutrición',
    isFavorite: false,
  },
  {
    id: 'p5',
    name: 'Deep Nutrition Bifásico',
    price: 399.00,
    description: 'Acondicionador bifásico sin enjuague que desenreda y protege el cabello de forma instantánea. Ideal para uso diario.',
    images: [require('../assets/images/products/deep-nutrition-bifasico.png')],
    rating: 4.4,
    reviewsCount: 75,
    category: 'Hidratación y Nutrición',
    isFavorite: false,
  },
  {
    id: 'p6',
    name: 'Deep Nutrition Mask',
    price: 449.00,
    description: 'Mascarilla ultra-nutritiva que repara las puntas abiertas y fortalece la estructura del cabello.',
    images: [require('../assets/images/products/deep-nutrition-mask.png')],
    rating: 4.7,
    reviewsCount: 110,
    category: 'Hidratación y Nutrición',
    isFavorite: false,
  },
  {
    id: 'p7',
    name: 'Hydrating Shampoo',
    price: 380.00,
    description: 'Shampoo de hidratación profunda para restaurar la humedad natural del cabello y evitar el frizz.',
    images: [require('../assets/images/products/hydrating-shampoo.png')],
    rating: 4.6,
    reviewsCount: 92,
    category: 'Hidratación y Nutrición',
    isFavorite: false,
  },
  {
    id: 'p8',
    name: 'Hydro System Moisturizing',
    price: 399.00,
    description: 'Sistema hidratante que deja el cabello suave, manejable y con un brillo espectacular. Ideal para cabello seco.',
    images: [require('../assets/images/products/hydro-system-moisturizing.png')],
    rating: 4.5,
    reviewsCount: 65,
    category: 'Hidratación y Nutrición',
    isFavorite: false,
  },
  {
    id: 'p9',
    name: 'Hydro Intensive Mask',
    price: 449.00,
    description: 'Mascarilla intensiva que proporciona una dosis extra de hidratación para reparar el cabello desde el interior.',
    images: [require('../assets/images/products/hydro-intensive-mask.png')],
    rating: 4.6,
    reviewsCount: 80,
    category: 'Hidratación y Nutrición',
    isFavorite: false,
  },
  {
    id: 'p10',
    name: 'Master Thermo Protector',
    price: 419.00,
    description: 'Protector térmico que defiende el cabello del calor de secadoras y planchas. No deja residuos y aporta brillo.',
    images: [require('../assets/images/products/master-thermo-protector.png')],
    rating: 4.8,
    reviewsCount: 210,
    category: 'Protección Térmica',
    isFavorite: false,
  },
  {
    id: 'p11',
    name: 'Fast Thermic',
    price: 389.00,
    description: 'Acelerador de secado que protege el cabello del calor y reduce el tiempo de estilizado.',
    images: [require('../assets/images/products/fast-thermic.png')],
    rating: 4.3,
    reviewsCount: 50,
    category: 'Protección Térmica',
    isFavorite: false,
  },
  {
    id: 'p12',
    name: 'Vitalizing Tonic Intensive Treatment',
    price: 499.00,
    description: 'Tónico capilar que fortalece el cuero cabelludo, estimula el crecimiento y previene la caída del cabello.',
    images: [require('../assets/images/products/vitalizing-tonic-intensive-treatment.png')],
    rating: 4.7,
    reviewsCount: 180,
    category: 'Crecimiento y Anti-caída',
    isFavorite: false,
  },
  {
    id: 'p13',
    name: 'Final Touch Spray',
    price: 349.00,
    description: 'Spray de acabado que aporta brillo y control al peinado, sin apelmazar el cabello.',
    images: [require('../assets/images/products/final-touch-spray.png')],
    rating: 4.4,
    reviewsCount: 65,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p14',
    name: '3h Cream',
    price: 399.00,
    description: 'Crema de peinado para control de frizz y definición de rizos. Proporciona hidratación prolongada.',
    images: [require('../assets/images/products/3h-cream.png')],
    rating: 4.5,
    reviewsCount: 78,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p15',
    name: 'Dazzling Hair Silk Frutos Rojos',
    price: 219.00,
    description: 'Seda capilar que aporta suavidad, brillo y un delicioso aroma a frutos rojos.',
    images: [require('../assets/images/products/dazzling-hair-silk-frutos-rojos.png')],
    rating: 4.6,
    reviewsCount: 115,
    category: 'Brillo y Sedas',
    isFavorite: false,
  },
  {
    id: 'p16',
    name: 'Dazzling Hair Silk Frutos Verdes',
    price: 219.00,
    description: 'Seda capilar que protege del calor y da un acabado sedoso, con una fragancia refrescante a frutos verdes.',
    images: [require('../assets/images/products/dazzling-hair-silk-frutos-verdes.png')],
    rating: 4.6,
    reviewsCount: 105,
    category: 'Brillo y Sedas',
    isFavorite: false,
  },
  {
    id: 'p17',
    name: 'Dazzling Hair Silk Uva',
    price: 219.00,
    description: 'Seda capilar de alta concentración que repara las puntas y da un brillo inigualable, con aroma a uva.',
    images: [require('../assets/images/products/dazzling-hair-silk-uva.png')],
    rating: 4.6,
    reviewsCount: 99,
    category: 'Brillo y Sedas',
    isFavorite: false,
  },
  {
    id: 'p18',
    name: 'Wasser',
    price: 0.00,
    description: 'Agua purificada para estilizar y refrescar el cabello, perfecta para reactivar rizos y peinados.',
    images: [require('../assets/images/products/wasser.png')],
    rating: 4.2,
    reviewsCount: 45,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p19',
    name: 'Pro Pluss',
    price: 399.00,
    description: 'Protector capilar que refuerza el cabello de raíz a punta, ideal para antes de tratamientos químicos.',
    images: [require('../assets/images/products/pro-pluss.png')],
    rating: 4.5,
    reviewsCount: 82,
    category: 'Reparación y Fuerza',
    isFavorite: false,
  },
  {
    id: 'p20',
    name: 'Water Pomade',
    price: 299.00,
    description: 'Pomada a base de agua para un peinado firme y sin residuos. Fácil de lavar.',
    images: [require('../assets/images/products/water-pomade.png')],
    rating: 4.4,
    reviewsCount: 60,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p21',
    name: 'Cera Gel',
    price: 219.00,
    description: 'Gel con efecto cera para un peinado de larga duración y con brillo. Ideal para estilos estructurados.',
    images: [require('../assets/images/products/cera-gel.png')],
    rating: 4.3,
    reviewsCount: 55,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p22',
    name: 'Cera Wax',
    price: 219.00,
    description: 'Cera con acabado mate que proporciona control y fijación sin brillo. Perfecta para estilos texturizados.',
    images: [require('../assets/images/products/cera-wax.png')],
    rating: 4.3,
    reviewsCount: 58,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p23',
    name: 'Anti Caída Men Hair Regeneration Complex',
    price: 0.00,
    description: 'Tratamiento intensivo para hombres que combate la caída del cabello y promueve el crecimiento. Fortalece el folículo.',
    images: [require('../assets/images/products/anti-caida-men-hair-regeneration-complex.png')],
    rating: 4.7,
    reviewsCount: 140,
    category: 'Crecimiento y Anti-caída',
    isFavorite: false,
  },
  {
    id: 'p24',
    name: 'Prodin Acelerador Crecimiento Barba Bigote',
    price: 489.00,
    description: 'Acelerador de crecimiento para barba y bigote, enriquecido con vitaminas y nutrientes esenciales.',
    images: [require('../assets/images/products/prodin-acelerador-crecimiento-barba-bigote.png')],
    rating: 4.5,
    reviewsCount: 90,
    category: 'Crecimiento y Anti-caída',
    isFavorite: false,
  },
  {
    id: 'p25',
    name: 'Shampoo 3 en 1 Smart Men',
    price: 319.00,
    description: 'Shampoo, acondicionador y gel de baño todo en uno. Formulado para las necesidades del hombre moderno.',
    images: [require('../assets/images/products/shampoo-3-en-1-smart-men.png')],
    rating: 4.4,
    reviewsCount: 70,
    category: 'Cuidado para Hombres',
    isFavorite: false,
  },
  {
    id: 'p26',
    name: 'Cera Gel Lady Style',
    price: 390.00,
    description: 'Cera en gel para mujer que ofrece fijación y control para peinados complejos, sin dejar residuos.',
    images: [require('../assets/images/products/cera-gel-lady-style.png')],
    rating: 4.4,
    reviewsCount: 68,
    category: 'Fijación y Moldeado',
    isFavorite: false,
  },
  {
    id: 'p27',
    name: 'Kit Playa Cuida Tu Cabello',
    price: 399.00,
    description: 'Kit de cuidado capilar esencial para proteger el cabello del sol, el cloro y la sal. Incluye shampoo y protector.',
    images: [require('../assets/images/products/kit-playa-cuida-tu-cabello.jpg')],
    rating: 4.5,
    reviewsCount: 130,
    category: 'Otros Tratamientos',
    isFavorite: false,
  },
  {
    id: 'p28',
    name: 'Gel de Afeitar',
    price: 299.00,
    description: 'Gel transparente para un afeitado preciso y suave. Minimiza la irritación y protege la piel.',
    images: [require('../assets/images/products/gel-de-afeitar.jpg')],
    rating: 4.3,
    reviewsCount: 52,
    category: 'Cuidado para Hombres',
    isFavorite: false,
  },
  {
    id: 'p29',
    name: 'Gel Post Afeitado',
    price: 299.00,
    description: 'Gel que calma e hidrata la piel después del afeitado, dejándola suave y fresca. Ayuda a cerrar los poros.',
    images: [require('../assets/images/products/gel-post-afeitado.jpg')],
    rating: 4.3,
    reviewsCount: 80,
    category: 'Cuidado para Hombres',
    isFavorite: false,
  },
];

export default products;
